"""The documented COM surface used by the adapter, with no runtime wrappers.

pywin32 provides dynamic dispatch. These structural interfaces type its known
Outlook API at the attachment boundary; mailbox data is explicitly mapped into
validated public models. All references remain on the worker's STA thread.
"""

from datetime import datetime
from typing import Protocol, TypeVar

TComItem = TypeVar("TComItem", covariant=True)


class IIndexedCollection(Protocol[TComItem]):
    @property
    def Count(self) -> int: ...
    def Item(self, index: int) -> TComItem: ...


class ICursorCollection(Protocol[TComItem]):
    def GetFirst(self) -> TComItem | None: ...
    def GetNext(self) -> TComItem | None: ...


class IIdentifiedItem(Protocol):
    @property
    def EntryID(self) -> str: ...


class IPropertyAccessor(Protocol):
    def GetProperty(self, name: str) -> object: ...


class IExchangeAddress(Protocol):
    @property
    def PrimarySmtpAddress(self) -> str: ...


class IAddressEntry(Protocol):
    @property
    def Type(self) -> str: ...
    @property
    def Address(self) -> str: ...
    @property
    def PropertyAccessor(self) -> IPropertyAccessor: ...
    def GetExchangeUser(self) -> IExchangeAddress | None: ...
    def GetExchangeDistributionList(self) -> IExchangeAddress | None: ...


class IRecipient(Protocol):
    @property
    def Name(self) -> str: ...
    @property
    def Type(self) -> int: ...
    @property
    def AddressEntry(self) -> IAddressEntry | None: ...


class IAttachment(Protocol):
    @property
    def FileName(self) -> str: ...
    @property
    def Size(self) -> int: ...


class IOutlookItem(IIdentifiedItem, Protocol):
    @property
    def Class(self) -> int: ...
    @property
    def Parent(self) -> "IFolder": ...
    @property
    def Subject(self) -> str: ...
    @property
    def ReceivedTime(self) -> datetime: ...
    @property
    def SentOn(self) -> datetime: ...
    @property
    def UnRead(self) -> bool: ...
    @property
    def SenderName(self) -> str: ...
    @property
    def SenderEmailType(self) -> str: ...
    @property
    def SenderEmailAddress(self) -> str: ...
    @property
    def Sender(self) -> IAddressEntry | None: ...
    @property
    def Recipients(self) -> IIndexedCollection[IRecipient]: ...
    @property
    def Attachments(self) -> IIndexedCollection[IAttachment]: ...
    @property
    def DownloadState(self) -> int: ...
    @property
    def Body(self) -> str: ...


class IItems(ICursorCollection[IOutlookItem], Protocol):
    def Restrict(self, expression: str) -> "IItems": ...
    def Sort(self, property_name: str, descending: bool) -> None: ...


class IFolders(IIndexedCollection["IFolder"], ICursorCollection["IFolder"], Protocol):
    pass


class IFolder(IIdentifiedItem, Protocol):
    @property
    def StoreID(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Folders(self) -> IFolders: ...
    @property
    def Items(self) -> IItems: ...


class IStore(Protocol):
    @property
    def StoreID(self) -> str: ...
    @property
    def DisplayName(self) -> str: ...
    def GetDefaultFolder(self, folder_type: int) -> IFolder | None: ...
    def GetRootFolder(self) -> IFolder: ...


class INamespace(Protocol):
    @property
    def Stores(self) -> IIndexedCollection[IStore]: ...
    @property
    def DefaultStore(self) -> IStore: ...
    def GetStoreFromID(self, store_id: str) -> IStore: ...
    def GetFolderFromID(self, folder_id: str, store_id: str | None) -> IFolder: ...
    def GetItemFromID(self, entry_id: str, store_id: str) -> IOutlookItem | None: ...


class IOutlookApplication(Protocol):
    @property
    def Version(self) -> str: ...
    def GetNamespace(self, name: str) -> INamespace: ...
