"""The documented COM surface used by the adapter, with no runtime wrappers.

pywin32 provides dynamic dispatch. These structural interfaces type its known
Outlook API at the attachment boundary; mailbox data is explicitly mapped into
validated public models. All references remain on the worker's STA thread.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Protocol, TypeVar

TComItem = TypeVar("TComItem", covariant=True)


class IIndexedCollection(Protocol[TComItem]):
    @property
    def Count(self) -> int: ...
    def Item(self, index: int) -> TComItem: ...


class ICursorCollection(Protocol[TComItem]):
    def GetFirst(self) -> TComItem | None: ...
    def GetNext(self) -> TComItem | None: ...


class IIdentifiedItem(Protocol):
    @property
    def EntryID(self) -> str: ...


class IPropertyAccessor(Protocol):
    def GetProperty(self, name: str) -> object: ...


class IExchangeAddress(Protocol):
    @property
    def PrimarySmtpAddress(self) -> str: ...


class IAddressEntry(Protocol):
    @property
    def Type(self) -> str: ...
    @property
    def Address(self) -> str: ...
    @property
    def PropertyAccessor(self) -> IPropertyAccessor: ...
    def GetExchangeUser(self) -> IExchangeAddress | None: ...
    def GetExchangeDistributionList(self) -> IExchangeAddress | None: ...


class IRecipient(Protocol):
    def Resolve(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def Type(self) -> int: ...
    @Type.setter
    def Type(self, value: int) -> None: ...
    @property
    def Resolved(self) -> bool: ...
    @property
    def AddressEntry(self) -> IAddressEntry | None: ...


class IAttachment(Protocol):
    @property
    def FileName(self) -> str: ...
    @property
    def Size(self) -> int: ...


class IRecipients(IIndexedCollection[IRecipient], Protocol):
    def Add(self, address: str) -> IRecipient: ...
    def ResolveAll(self) -> bool: ...


class IInspector(Protocol):
    def Activate(self) -> None: ...


class IColumns(Protocol):
    def Add(self, name: str) -> object: ...


class IRow(Protocol):
    def Item(self, name: str) -> object: ...
    def BinaryToString(self, name: str) -> str: ...


class ITable(Protocol):
    @property
    def Columns(self) -> IColumns: ...
    @property
    def EndOfTable(self) -> bool: ...
    def MoveToStart(self) -> None: ...
    def GetNextRow(self) -> IRow: ...


class IConversation(Protocol):
    def GetTable(self) -> ITable: ...


class IDispatchReference(Protocol):
    def GetIDsOfNames(self, name: str) -> int: ...
    def Invoke(
        self, dispatch_id: int, locale: int, flags: int, result: bool, value: "IAccount"
    ) -> object: ...


class IOutlookItem(IIdentifiedItem, Protocol):
    @property
    def _oleobj_(self) -> IDispatchReference: ...
    @property
    def Class(self) -> int: ...
    @property
    def Parent(self) -> "IFolder": ...
    @property
    def Subject(self) -> str: ...
    @Subject.setter
    def Subject(self, value: str) -> None: ...
    @property
    def ReceivedTime(self) -> datetime: ...
    @property
    def LastModificationTime(self) -> datetime: ...
    @property
    def SentOn(self) -> datetime: ...
    @property
    def UnRead(self) -> bool: ...
    @property
    def SenderName(self) -> str: ...
    @property
    def SenderEmailType(self) -> str: ...
    @property
    def SenderEmailAddress(self) -> str: ...
    @property
    def Sender(self) -> IAddressEntry | None: ...
    @property
    def Recipients(self) -> IRecipients: ...
    @property
    def Attachments(self) -> IIndexedCollection[IAttachment]: ...
    @property
    def DownloadState(self) -> int: ...
    @property
    def Body(self) -> str: ...
    @Body.setter
    def Body(self, value: str) -> None: ...
    @property
    def BodyFormat(self) -> int: ...
    @BodyFormat.setter
    def BodyFormat(self, value: int) -> None: ...
    @property
    def SendUsingAccount(self) -> "IAccount | None": ...
    @property
    def SentOnBehalfOfName(self) -> str: ...
    @property
    def Sent(self) -> bool: ...
    @property
    def Saved(self) -> bool: ...
    @property
    def ConversationID(self) -> str: ...
    @property
    def Categories(self) -> str: ...
    @property
    def Importance(self) -> int: ...
    @property
    def PropertyAccessor(self) -> IPropertyAccessor: ...
    @property
    def GetInspector(self) -> IInspector: ...
    def Display(self, modal: bool = False) -> None: ...
    def Save(self) -> None: ...
    def Send(self) -> None: ...
    def Reply(self) -> "IOutlookItem": ...
    def ReplyAll(self) -> "IOutlookItem": ...
    def GetConversation(self) -> IConversation | None: ...


class IItems(ICursorCollection[IOutlookItem], Protocol):
    def Restrict(self, expression: str) -> "IItems": ...
    def Sort(self, property_name: str, descending: bool) -> None: ...
    def Add(self, item_type: str) -> IOutlookItem: ...


class IFolders(IIndexedCollection["IFolder"], ICursorCollection["IFolder"], Protocol):
    pass


class IFolder(IIdentifiedItem, Protocol):
    @property
    def StoreID(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Folders(self) -> IFolders: ...
    @property
    def Items(self) -> IItems: ...


class IStore(Protocol):
    @property
    def StoreID(self) -> str: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def IsConversationEnabled(self) -> bool: ...
    def GetDefaultFolder(self, folder_type: int) -> IFolder | None: ...
    def GetRootFolder(self) -> IFolder: ...


class IAccount(Protocol):
    @property
    def SmtpAddress(self) -> str: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def DeliveryStore(self) -> IStore | None: ...


class INamespace(Protocol):
    def CreateRecipient(self, name: str) -> IRecipient: ...
    @property
    def Accounts(self) -> IIndexedCollection[IAccount]: ...
    @property
    def Stores(self) -> IIndexedCollection[IStore]: ...
    @property
    def DefaultStore(self) -> IStore: ...
    def GetStoreFromID(self, store_id: str) -> IStore: ...
    def GetFolderFromID(self, folder_id: str, store_id: str | None) -> IFolder: ...
    def GetItemFromID(self, entry_id: str, store_id: str) -> IOutlookItem | None: ...


class IOutlookApplication(Protocol):
    @property
    def Version(self) -> str: ...
    def GetNamespace(self, name: str) -> INamespace: ...


@dataclass(frozen=True)
class ConversationItem:
    """Worker-only traversal value; COM objects never enter public output models."""

    EntryID: str
    item: IOutlookItem
    store_id: str
