"""Named values for public contracts and operational state."""

from enum import StrEnum


class EToolName(StrEnum):
    OUTLOOK_STATUS = "outlook_status"
    LIST_MAILBOXES = "list_mailboxes"
    LIST_FOLDERS = "list_folders"
    RECENT_EMAILS = "recent_emails"
    SEARCH_EMAILS = "search_emails"
    READ_EMAIL = "read_email"
    OPEN_EMAIL = "open_email"
    CREATE_DRAFT = "create_draft"
    REPLY_TO_EMAIL = "reply_to_email"
    READ_CONVERSATION = "read_conversation"
    PREPARE_SEND = "prepare_send"
    SEND_DRAFT = "send_draft"


class EErrorCode(StrEnum):
    REFERENCE_EXPIRED = "REFERENCE_EXPIRED"
    REFERENCE_LIMIT = "REFERENCE_LIMIT"
    UNSUPPORTED_PLATFORM = "UNSUPPORTED_PLATFORM"
    OUTLOOK_NOT_INSTALLED = "OUTLOOK_NOT_INSTALLED"
    OUTLOOK_UNAVAILABLE = "OUTLOOK_UNAVAILABLE"
    OUTLOOK_TIMEOUT = "OUTLOOK_TIMEOUT"
    ACCESS_DENIED = "ACCESS_DENIED"
    STORE_NOT_FOUND = "STORE_NOT_FOUND"
    FOLDER_NOT_FOUND = "FOLDER_NOT_FOUND"
    ITEM_NOT_FOUND = "ITEM_NOT_FOUND"
    BODY_UNAVAILABLE = "BODY_UNAVAILABLE"
    METADATA_UNAVAILABLE = "METADATA_UNAVAILABLE"
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    CURSOR_EXPIRED = "CURSOR_EXPIRED"
    SEARCH_SESSION_LIMIT = "SEARCH_SESSION_LIMIT"
    SERVER_BUSY = "SERVER_BUSY"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    CAPABILITY_DISABLED = "CAPABILITY_DISABLED"
    WRITE_OUTCOME_UNKNOWN = "WRITE_OUTCOME_UNKNOWN"
    UNSUPPORTED_COMPOSITION = "UNSUPPORTED_COMPOSITION"
    CONFIRMATION_INVALID = "CONFIRMATION_INVALID"
    DRAFT_CHANGED = "DRAFT_CHANGED"
    CONVERSATION_UNAVAILABLE = "CONVERSATION_UNAVAILABLE"


class EStopReason(StrEnum):
    EXHAUSTED = "exhausted"
    PAGE_LIMIT = "page_limit"
    SCAN_LIMIT = "scan_limit"
    TIME_BUDGET = "time_budget"


class ERecipientKind(StrEnum):
    TO = "to"
    CC = "cc"
    BCC = "bcc"
    UNKNOWN = "unknown"


class EReferenceKind(StrEnum):
    STORE = "s"
    FOLDER = "f"
    ITEM = "m"
